# ENVIRONMENT-BASED DOCKER-COMPOSE FILE
version: '3.9'

services:
#=======================CATALOG API==============================
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      # AS STATED IN THE CAVEATS SECTION AT https://hub.docker.com/_/mongo
      - mongo_data:/data/db   

  catalogapi:
    container_name: catalogapi
    depends_on:
      - catalogdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
        # NO LOCALHOST HERE, INSIDE A CONTAINER, ONLY USE CONTAINER NAMES
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        # IF THERE'S ANY PROBLEM WITH THE DB, STOP THE CONTAINER
    ports:
        # EXTERNAL:INTERNAL PORT FORWARDING
      - "8000:8080"
      
#=======================SHOPPING CART API========================
  redis-cache:
    container_name: sc-redis
    restart: always
    ports:
      - "6379:6379"
      #Composer must mirror all settings in appsettings.json
  shoppingcartapi:
    container_name: shoppingcartapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:Redis=redis-cache://localhost:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    ports:
        # EXTERNAL:INTERNAL PORT FORWARDING
      - "8001:8080"
    depends_on:
      - redis-cache

#=======================DISCOUNT gRPC========================
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
      
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:npgsql=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8003:8080"

