version: '3.9'

services:

#=======================CATALOG API==============================
  catalogdb:
    # OFFICIAL MONGO IMAGE NAME
    image: mongo
    
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/CatalogAPI/Dockerfile
      
#=======================SHOPPING CART API========================
  shoppingcartapi:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCartAPI/Dockerfile

  redis-cache:
    # OFFICIAL REDIS IMAGE NAME
    image: redis:alpine
    
#=======================DISCOUNT gRPC========================
  discountdb:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount.gRPC/Dockerfile

volumes:
  mongo_data: 
  postgres_data:
  pgadmin_data:



