# ENVIRONMENT-BASED DOCKER-COMPOSE FILE
version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      # AS STATED IN THE CAVEATS SECTION AT https://hub.docker.com/_/mongo
      - mongo_data:/data/db   

  catalogapi:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
        # NO LOCALHOST HERE, INSIDE A CONTAINER, ONLY USE CONTAINER NAMES
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        # IF THERE'S ANY PROBLEM WITH THE DB, STOP THE CONTAINER
    depends_on:
      - catalogdb
    ports:
        # EXTERNAL:INTERNAL PORT FORWARDING
      - "8000:8080"

  shoppingcartcache:
    container_name: shoppingcartcache
    restart: always
    ports:
      - "6379:6379"
    #volumes:
    # - ./redis_data:/data
      

  shoppingcartapi:
    container_name: shoppingcartapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "CacheSettings:ConnectionString=shoppingcartcache:6379"
    depends_on:
      - shoppingcartcache
    ports:
        # EXTERNAL:INTERNAL PORT FORWARDING
      - "8001:8080"

