version: '3.4'

services:
  catalogdb:
    # OFFICIAL MONGO IMAGE NAME
    image: mongo

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/CatalogAPI/Dockerfile

  shoppingcartcache:
    # OFFICIAL REDIS IMAGE NAME
    image: redis:alpine

  shoppingcartapi:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCartAPI/Dockerfile

volumes:
  mongo_data: 
  redis_data:

