// <auto-generated />
using Discount.gRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Discount.gRPC.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240209051118_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Discount.gRPC.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coupon");

                    b.HasData(
                        new
                        {
                            Id = 1830626770,
                            Amount = -1888717867,
                            Description = "Practical",
                            ProductName = "SQL"
                        },
                        new
                        {
                            Id = 84652876,
                            Amount = 1261692699,
                            Description = "solid state",
                            ProductName = "Industrial"
                        },
                        new
                        {
                            Id = 1458675486,
                            Amount = -556765606,
                            Description = "Lodge",
                            ProductName = "Borders"
                        },
                        new
                        {
                            Id = -118955176,
                            Amount = 164385074,
                            Description = "View",
                            ProductName = "XSS"
                        },
                        new
                        {
                            Id = 999898981,
                            Amount = -1018852053,
                            Description = "platforms",
                            ProductName = "lavender"
                        },
                        new
                        {
                            Id = -1301465039,
                            Amount = -1387128416,
                            Description = "invoice",
                            ProductName = "access"
                        },
                        new
                        {
                            Id = -615034807,
                            Amount = -1211101645,
                            Description = "deposit",
                            ProductName = "Handmade Fresh Computer"
                        },
                        new
                        {
                            Id = -1965710375,
                            Amount = -1331833248,
                            Description = "Way",
                            ProductName = "real-time"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
